'use client'
import React,{useMemo,useRef}from'react'
import{Canvas,useFrame}from'@react-three/fiber'
import{OrbitControls,Sparkles,Stars}from'@react-three/drei'
import{EffectComposer,Bloom,Vignette}from'@react-three/postprocessing'
import * as THREE from'three'
function ThrusterParticles(){const count=300;const positions=useMemo(()=>{const a=new Float32Array(count*3);for(let i=0;i<count;i++){a[i*3+0]=(Math.random()-.5)*.08;a[i*3+1]=-0.8-Math.random()*.2;a[i*3+2]=(Math.random()-.5)*.08}return a},[]);const ref=useRef<THREE.Points>(null!);useFrame((state)=>{const t=state.clock.getElapsedTime();const att=ref.current.geometry.attributes.position as THREE.BufferAttribute;for(let i=0;i<count;i++){let y=att.getY(i)+(Math.sin(t*5+i)*.01+.02);if(y>-0.3)y=-0.9;att.setY(i,y)}att.needsUpdate=true});return(<points ref={ref} position={[0,-0.2,0]}><bufferGeometry><bufferAttribute attach='attributes-position' args={[positions,3]}/></bufferGeometry><pointsMaterial color='#fb923c' size={0.02} sizeAttenuation depthWrite={false}/></points>) }
function Rocket(){const g=useRef<THREE.Group>(null!);const flame=useRef<THREE.Mesh>(null!);useFrame((state)=>{const t=state.clock.getElapsedTime();g.current.position.y=Math.sin(t*1.2)*.1;g.current.rotation.z=Math.sin(t*.6)*.05;if(flame.current){const s=1+Math.sin(t*8)*.2;flame.current.scale.set(1,s,1);(flame.current.material as THREE.MeshStandardMaterial).emissiveIntensity=1.2+Math.sin(t*10)*.6}});return(<group ref={g} position={[0,0,0]}><mesh castShadow><cylinderGeometry args={[.25,.3,1.2,32]}/><meshStandardMaterial color='#e2e8f0' metalness={.4} roughness={.2}/></mesh><mesh position={[0,.7,0]} castShadow><coneGeometry args={[.25,.5,32]}/><meshStandardMaterial color='#94a3b8' metalness={.5} roughness={.25}/></mesh><mesh position={[0,.2,.26]}><circleGeometry args={[.12,32]}/><meshStandardMaterial color='#0ea5e9' emissive='#075985' emissiveIntensity={.6}/></mesh>{[-1,1].map((s,i)=>(<mesh key={i} position={[.23*s,-.4,0]} rotation={[0,0,Math.PI/8*s]}><boxGeometry args={[.05,.4,.2]}/><meshStandardMaterial color='#334155' metalness={.3} roughness={.6}/></mesh>))}<mesh ref={flame} position={[0,-.8,0]}><coneGeometry args={[.12,.4,16]}/><meshStandardMaterial color='#fb923c' emissive='#ef4444' emissiveIntensity={1.5}/></mesh><ThrusterParticles/></group>) }
function SceneInner(){return(<><ambientLight intensity={.6}/><directionalLight position={[3,3,2]} intensity={1.2} castShadow/><Rocket/><Sparkles noise={.25} size={2} scale={[6,3,2]} speed={.5} count={160} position={[0,0,0]}/><Stars radius={80} depth={50} count={4000} factor={4} saturation={0} fade speed={.5}/><EffectComposer><Bloom intensity={.7} luminanceThreshold={.18} luminanceSmoothing={.9}/><Vignette eskil={false} offset={.15} darkness={.75}/></EffectComposer><OrbitControls enablePan={false} enableZoom={false} enableRotate={false}/></>) }
export default function ThreeScene(){return(<Canvas className='fixed inset-0 -z-20 pointer-events-none' camera={{position:[0,0,5],fov:45}} shadows><SceneInner/></Canvas>) }
